services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: curl -sSL https://install.python-poetry.org | python3 - && poetry install
    startCommand: poetry run uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
